blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions & Questions
    url: https://github.com/Nistro-dev/cse-saas/discussions
    about: Pour les questions générales et discussions
  - name: 📖 Documentation
    url: https://github.com/Nistro-dev/cse-saas/wiki
    about: Consultez la documentation du projet
